### ISSUE TITLE
Sensitive Info

### ISSUE THREAD

**Issue by aaronwbrown** [tophercullen/sisense#1]
Hi Topher, 

My name is Aaron Brown, and I am a Senior Security Engineer at Sisense. This public repo was brought to my attention, due to its holding of sensitive information. If you could please do one of the following, it would be greatly appreciated:

- Remove the repo entirely
- Make the repository private
- Keep the repo public, but remove the secrets, and rewrite the git history so they are not persisted

The primary file in question is [/templates/default/default.yaml.erb](https://github.com/tophercullen/sisense/blob/master/templates/default/default.yaml.erb). If you choose to keep the repository public, please perform a thorough review of the code to make sure nothing else is disclosed. 

Please contact me if you have any questions. I am more than happy to help.

Best,
Aaron

**Comment by tophercullen** [comment]
This code is in excess of 5 years old, and is effectively useful for general reference only. Any secrets shouldn't be relevant anymore. If you feel otherwise, then I can delete the repo. It has little value at this point as I'm sure the sisense config has changed.

**Comment by aaronwbrown** [comment]
@tophercullen - thanks for taking the time to respond and your willingness to address my request. It is not a matter of whether the credentials are still valid, but rather centered around best practices in secure software development, including secrets management. A good resource for these best practices is the [OWASP Proactive Controls](https://owasp.org/www-project-proactive-controls/v3/en/0x04-introduction.html). One of which is [Protecting Data Everywhere](https://owasp.org/www-project-proactive-controls/v3/en/c8-protect-data-everywhere), with a section on managing application secrets.

All that said, if you wish to keep the repo for reference, please make it private.

Thanks again, 
Aaron
